### ISSUE TITLE
FRONT PTFE HOLDER B15_EXPERIMENTAL.stl

### ISSUE THREAD

**Issue by slaesh** [davidkerny/BUZA-ULTIMULTI#4]
just a note, dont know if it is on purpose or not..
the B15 experimental part uses M3x18 screws, instead of M3x10 like the rest of the parts :)

**Comment by davidkerny** [comment]
Hi! 
Do you mean the COLLET HOLDR C7 (the rear PTFE holder)?
M3x10 might be a bit too short in this place. 
Two M3x18 bolts are used to hold the electronics on top of MMU2S / MMU3 - you can reuse those :)

(the Rear PTFE holder on MM3S as well as collet holder on MMU3 both use M3x10 bolts in this place - but these parts are mounted slightly differently.)
David

**Comment by slaesh** [comment]
Hey David, thanks for that info do! :)

Oh, yeah. sh*t! it's the C7 🙈🙈 You know your parts though! ;)

I have enough screws .. was just wondering and wanted to ask you.. since I thought it was the experimental part 😅 :))

Awesome work btw! Have a great 2024
