### ISSUE TITLE
SELECTOR_B18.stl

### ISSUE THREAD

**Issue by slaesh** [davidkerny/BUZA-ULTIMULTI#5]
this part maybe could need some more strength at the clamping part:

![image](https://github.com/davidkerny/BUZA-ULTIMULTI/assets/55546823/d24d7fc9-b333-4f6f-a567-59f14b11e007)

it broke, i did not forced it too much.. its just plastic! ;)
but the SuperFINDA was still loose.. after tightening it up enough.. like 5-10 seconds later.. I heard a "click" :(

**Comment by davidkerny** [comment]
Hi! 
Thanks for the report. 
This has been happening once in a while on the MMU3 selectors too. I've been searching for a solution but then found the craked finda holders still serve the function so I left it as it was. 
Maybe the FINDA-holding part should be thinner, less constrained, more flexible. Let me know if you have ideas to make it work with different materials and print settings :) 

D.

**Comment by slaesh** [comment]
Yeah I will let it sit for now too :)) seems to do it's job 🦾
Hopefully being able to do some test prints on the weekend 🤝😎
